name: Weekly Update Hosts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update_hosts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove existing hosts (optional)
        run: rm -f hosts || true

      - name: Download script
        run: curl -sSfL ${{ secrets.SCRIPT }} -o script.py

      - name: Run Python script
        run: python3 script.py

      - name: Add generated hosts.txt
        run: git add hosts

      - name: Commit changes
        run: |
          git config --local user.name "elliottophellia"
          git config --local user.email "me@rei.my.id"
          git commit -m "🚀 Update: $(date +'%Y-%m-%d %H:%M:%S %Z')"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        run: git push origin +main